<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <ImplicitUsings>true</ImplicitUsings>
    <RootNamespace>AotAssemblyScan</RootNamespace>
    <PackageId>AotAssemblyScan.Abstractions</PackageId>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>CS9113</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../Readme.md" Pack="true" PackagePath="/"/>
  </ItemGroup>

</Project>
