//HintName: DefaultAssembly2_AssemblyExtensions_GetMarkedTypes_Generated.cs
// <auto-generated />

namespace DefaultAssembly2
{
    public static partial class AssemblyExtensions
    {
        public static partial System.Collections.Generic.IReadOnlyList<System.Type> GetMarkedTypes()
        {
            return new System.Type[] { typeof(DefaultAssembly1.AssemblyExtensions), typeof(DefaultAssembly2.AssemblyExtensions) };
        }
    }
}
