//HintName: DefaultAssembly_AssemblyExtensions_GetMarkedTypes_Generated.cs
// <auto-generated />

namespace DefaultAssembly
{
    public static partial class AssemblyExtensions
    {
        public static partial System.Type[] GetMarkedTypes()
        {
            return new Type[] { typeof(IMarker) };
        }
    }
}
