//HintName: DefaultAssembly_AssemblyExtensions_GetMarkedTypes_Generated.cs
// <auto-generated />

namespace DefaultAssembly
{
    public static partial class AssemblyExtensions
    {
        public static partial System.Collections.Generic.IReadOnlyList<System.Type> GetMarkedTypes()
        {
            return new Type[] { typeof(Company.Project.Classes.MarkedWithAttributeClass), typeof(Company.Project.Classes.MarkedWith2AttributesClass), typeof(Company.Project.Records.MarkedWithAttributeRecord), typeof(Company.Project.Structs.MarkedWithAttributeStruct) };
        }
    }
}
