//HintName: DefaultAssembly_AssemblyExtensions_GetMarkedTypes_Generated.cs
// <auto-generated />

namespace DefaultAssembly
{
    public static partial class AssemblyExtensions
    {
        public static partial System.Collections.Generic.IReadOnlyList<System.Type> GetMarkedTypes()
        {
            return new Type[] { typeof(IMarker), typeof(IMarker2) };
        }
    }
}
