//HintName: DefaultAssembly2_AssemblyExtensions_GetMarkedTypes_Generated.cs
// <auto-generated />

using System;
using System.Collections.Generic;

namespace DefaultAssembly2
{
    public static partial class AssemblyExtensions
    {
        public static partial IReadOnlyList<Type> GetMarkedTypes()
        {
            return new Type[] { typeof(IMarker), typeof(Company.Project.Classes.MarkedWithIntefaceClass), typeof(Company.Project.Records.MarkedWithIntefaceRecord), typeof(Company.Project.Structs.MarkedWithIntefaceStruct) };
        }
    }
}
