//HintName: DefaultAssembly_AssemblyExtensions_GetMarkedTypes_Generated.cs
// <auto-generated />

namespace DefaultAssembly
{
    public static partial class AssemblyExtensions
    {
        public static partial System.Collections.Generic.ICollection<System.Type> GetMarkedTypes()
        {
            return new Type[] { typeof(IMarker), typeof(Company.Project.Classes.MarkedWithIntefaceClass), typeof(Company.Project.Records.MarkedWithIntefaceRecord), typeof(Company.Project.Structs.MarkedWithIntefaceStruct), typeof(DefaultAssembly.AssemblyExtensions) };
        }
    }
}
