//HintName: DefaultAssembly1_AssemblyExtensions_GetMarkedTypes_Generated.cs
// <auto-generated />

namespace DefaultAssembly1
{
    public static partial class AssemblyExtensions
    {
        public static partial System.Collections.Generic.IReadOnlyList<System.Type> GetMarkedTypes()
        {
            return new System.Type[] { typeof(Company.Project.Classes.MarkedWith2InterfacesClass) };
        }
    }
}
